name: CD - $(Rev:r) - $(SourceBranchName)

trigger:
    - main





jobs:
    release:
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash

        steps:
            - uses: actions/checkout@v4

            - name: Create new release
              run: gh release create "linters-$(date +%Y-%m-%d)-(${{ github.run_number }})" --generate-notes --latest
              env:
                  GH_TOKEN: ${{ github.token }}
