parameters:
    - name: path_to_linters_submodule_root
      type: string
    - name: path_back_to_repository_root
      type: string
    - name: run_gitignore_linter
      type: boolean
      default: true
    - name: run_gitattributes_linter
      type: boolean
      default: true
    - name: run_cspell_configuration_linter
      type: boolean
      default: true
    - name: run_prettier_ignore_linter
      type: boolean
      default: true
    - name: run_cspell_linter
      type: boolean
      default: true
    - name: run_prettier_linter
      type: boolean
      default: true
    - name: run_psscript_analyzer_linter
      type: boolean
      default: true
    - name: run_clang_tools_linter
      type: boolean
      default: true


stages:
    - stage: LintingPowerShell
      displayName: Linting (PowerShell)
      jobs:
        - job: InstallLintingDependencies
          displayName: Install linting dependencies
          strategy:
          maxParallel: 3
          matrix:  # TODO: can this be made in to array like github actions?
              linux:
                  imageName: "ubuntu-latest"
              macos:
                  imageName: "macos-latest"
              windows:
                  imageName: "windows-latest"
          pool:
              vmImage: $(imageName)
          steps:
            - checkout: self
              submodules: true

            # TODO: check that other jobs skip if this fails
            - task: PowerShell@2
              displayName: Install linting dependencies
              inputs:
                targetType: inline
                script: |
                    Import-Module ${{ parameters.path_to_linters_submodule_root }}/linters-powershell/Linters.psd1
                    Install-LintingDependencies -PathToLintersSubmodulesRoot ${{ parameters.path_to_linters_submodule_root }} -Verbose

            - task: PowerShell@2
              displayName: Run gitignore linter
              condition: and(succeededOrFailed(), ${{ parameters.run_gitignore_linter }})
              inputs:
                targetType: inline
                script: |
                    Import-Module ${{ parameters.path_to_linters_submodule_root }}/linters-powershell/Linters.psd1
                    Test-GitIgnoreFile -Verbose

            - task: PowerShell@2
              displayName: Run gitattributes linter
              condition: and(succeededOrFailed(), ${{ parameters.run_gitattributes_linter }})
              inputs:
                targetType: inline
                script: |
                    Import-Module ${{ parameters.path_to_linters_submodule_root }}/linters-powershell/Linters.psd1
                    Test-GitAttributesFile -Verbose

            - task: PowerShell@2
              displayName: Run cspell configuration linter
              condition: and(succeededOrFailed(), ${{ parameters.run_cspell_configuration_linter }})
              inputs:
                targetType: inline
                script: |
                    Import-Module ${{ parameters.path_to_linters_submodule_root }}/linters-powershell/Linters.psd1
                    Test-CSpellConfiguration -Verbose

            - task: PowerShell@2
              displayName: Run cspell
              condition: and(succeededOrFailed(), ${{ parameters.run_cspell_linter }})
              inputs:
                targetType: inline
                script: |
                    Import-Module ${{ parameters.path_to_linters_submodule_root }}/linters-powershell/Linters.psd1
                    Test-CodeUsingCSpell -PathToLintersSubmodulesRoot ${{ parameters.path_to_linters_submodule_root }} -PathBackToRepositoryRoot ${{ parameters.path_back_to_repository_root }} -Verbose

            - task: PowerShell@2
              condition: and(succeededOrFailed(), ${{ parameters.run_prettier_linter }})
              displayName: Run prettier
              inputs:
                targetType: inline
                script: |
                    Import-Module ${{ parameters.path_to_linters_submodule_root }}/linters-powershell/Linters.psd1
                    Test-CodeUsingPrettier -PathToLintersSubmodulesRoot ${{ parameters.path_to_linters_submodule_root }} -PathBackToRepositoryRoot ${{ parameters.path_back_to_repository_root }} -Verbose

            - task: PowerShell@2
              displayName: Run PSScriptAnalyzer
              condition: and(succeededOrFailed(), ${{ parameters.run_psscript_analyzer_linter }})
              inputs:
                targetType: inline
                script: |
                    Import-Module ${{ parameters.path_to_linters_submodule_root }}/linters-powershell/Linters.psd1
                    Test-CodeUsingPSScriptAnalyzer -PathToLintersSubmodulesRoot ${{ parameters.path_to_linters_submodule_root }} -Verbose

            - task: Bash@3
              displayName: Run clang tools
              condition: and(succeededOrFailed(), ${{ parameters.run_clang_tools_linter }})
              inputs:
                targetType: inline
                script: |
                  # Install the ninja and the latest version of clang-tidy and clang-format
                  if [ "{{ matrix.os }}" = macos-latest ]
                  then
                      brew install ninja
                      brew install llvm
                      # Override pre-installed clang by adding to the path
                      export PATH="/opt/homebrew/opt/llvm/bin:$PATH"
                  fi

                  if [ "{{ matrix.os }}" = ubuntu-latest ]
                  then
                      sudo apt-get install ninja-build

                      # Install brew to get latest llvm and clang tools
                      test -d ~/.linuxbrew && eval "$(~/.linuxbrew/bin/brew shellenv)"
                      test -d /home/linuxbrew/.linuxbrew && eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
                      echo "eval \"\$($(brew --prefix)/bin/brew shellenv)\"" >> ~/.bashrc
                      export PATH="$HOME/.linuxbrew/bin:$PATH"

                      brew install llvm
                  fi

                  if [ "{{ matrix.os }}" = windows-latest ]
                  then
                      choco install ninja -y
                      choco upgrade llvm -y
                  fi

                  # Configure CMake to create the "compile_commands.json" file
                  cmake -S . -B ./build -G "Ninja"

                  pwsh -command "Import-Module ${{ parameters.path_to_linters_submodule_root }}/linters-powershell/Linters.psd1; Test-CodeUsingClangTools -PathToLintersSubmodulesRoot ${{ parameters.path_to_linters_submodule_root }} -Verbose"
