# MD003/heading-style : Heading style
MD003:
  style: "atx"
# MD004/ul-style : Unordered list style
MD004:
  style: "dash"
# MD009/no-trailing-spaces : Trailing spaces
MD009:
  # Spaces for line break
  br_spaces: 0
  # Include unnecessary breaks
  strict: true
# MD013/line-length : Line length
MD013:
  # Number of characters
  line_length: 128
  # Number of characters for headings
  heading_line_length: 128
  # Include code blocks
  code_blocks: false
  # Include tables
  tables: false
# MD029/ol-prefix : Ordered list item prefix
MD029:
  # List style
  style: "one"
# MD046/code-block-style : Code block style
MD046:
  # Block style
  style: "fenced"
# MD048/code-fence-style : Code fence style
MD048:
  # Code fence style
  style: "backtick"
# MD049/emphasis-style : Emphasis style
MD049:
  # Emphasis style
  style: "asterisk"
# MD050/strong-style : Strong style
MD050:
  # Strong style
  style: "asterisk"
# MD055/table-pipe-style : Table pipe style
MD055:
  # Table pipe style
  style: "leading_and_trailing"
