name: Continuous Integration

run-name: CI - ${{ github.run_number }} - ${{ github.head_ref }}

on:
    pull_request:
        branches:
            - main

jobs:
    linters-ps1:
        uses: J-Afzal/Linters/.github/workflows/workflow-templates/Linting-ps1.yml@main
