name: Continuous Integration

run-name: CI - ${{ github.run_number }} - ${{ github.head_ref }}

on:
    pull_request:
        branches:
            - main

jobs:
    linting:
        uses: ./.github/workflows/Linting.yml
        with:
            path_to_linters_submodule_root: "."
            path_back_to_repository_root: "."
            run_powershell_linters: true
