name: Continuous Deployment

run-name: CD - ${{ github.run_number }} - ${{ github.ref }}

on:
    push:
        branches:
            - main

jobs:
    release:
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: pwsh

        steps:
            - uses: actions/checkout@v4

            - name: Create new release
              run: |
                  $currentDate = Get-Date -Format "yyyy-MM-dd"
                  gh release create "linters-$currentDate" --generate-notes --latest
              env:
                  GH_TOKEN: ${{ github.token }}
